Update build script

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -28,15 +28,15 @@ jobs:
           pip install .
       - name: Generate plugin
         run: |
-          create-inventree-plugin --default --output my_plugin
-          test -d my_plugin
-          test -d my_plugin/MyCustomPlugin
-          test -d my_plugin/MyCustomPlugin/src
-          test -f my_plugin/MyCustomPlugin/src/__init__.py
-          test -f my_plugin/MyCustomPlugin/src/plugin.py
-          test -f my_plugin/MyCustomPlugin/README.md
+          create-inventree-plugin --default --output output
+          test -d output || echo "Output directory not found"
+          test -d output/MyCustomPlugin || echo "Plugin directory not found"
+          test -d output/MyCustomPlugin/src || echo "Source directory not found"
+          test -f output/MyCustomPlugin/src/__init__.py || echo "__init__.py not found"
+          test -f output/MyCustomPlugin/src/plugin.py || echo "plugin.py not found"
+          test -f output/MyCustomPlugin/README.md || echo "README.md not found"
       - name: Build and Install Plugin
         run: |
-          cd my_plugin
+          cd output
           flake8 .
           pip install .
